on:
  - push
jobs:
  deploy:
    name: Web site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install ikiwiki libtext-multimarkdown-perl libimage-magick-perl
      - run: mkdir ../html
      - run: ./bin/build-site . ../html
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: S3 Sync
        run: |
          aws s3 sync --acl public-read ../html s3://webconverger.org --delete
